### ISSUE TITLE
当分页查询的时候存在的问题可以优化一下

### ISSUE THREAD

**Issue by PhoenixBackendon** [wangzhongyang007/goframe-shop-v2#15]
![image](https://github.com/wangzhongyang007/goframe-shop-v2/assets/100568933/a90ff60f-16ef-41cf-bef9-83ebad6d0d18)
我发现如果仅仅根据total的数据量来创建List这样的操作似乎不太好，我们可以通过我画框的地方来做一下兜底操作，当超出总量能显示的数据时，比起返回一个空切片来讲，返回nil或者给一个异常说明下一页无数据更好一些，对前端也友好。

**Comment by wangzhongyang007** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by wangzhongyang007** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
